apiVersion: v1
kind: Service
metadata:
  name: ranking-service
spec:
  selector:
    app: ranking
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ranking
spec:
  selector:
    matchLabels:
      app: ranking
  replicas: 2
  template:
    metadata:
      labels:
        app: ranking
    spec:
      containers:
      - name: ranking
        image: ranking_deploy:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
